package javaEcxeption;

public class tryCatchBlock {

	public static void main(String[] args) {
         try {
//        	 System.out.print(10/0);
        	 System.out.print("Siddhu");
         } catch(Exception e) {
//        	 System.out.println("exception occurs");
         }
         finally {
        	 System.out.println("Finally block exicuteted");
         }
	}

}
