package com.ecxeption;

public class tryCatch {

	public static void main(String[] args) throws ArithmeticException {
    int num=10;
    try {
    	System.out.println(num/2);
    }catch (Exception e) {
		System.out.println(num/2);
	}
    finally {
    	System.out.println("finally block");
    }
    System.out.println("hi ");
	}

}
